### PR TITLE
adds markdown support

### PR DESCRIPTION
**Pull request by gabrielcsapo**
- makes turtler a class instead of a function
- adds the ability to render a markdown table `*instance*.markdown()`

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
thoughts @anusaini?

**Comment by anusaini** [comment]
Checkout #6

**Comment by anusaini** [comment]
Looks good

**Comment by gabrielcsapo** [comment]
Is #6 needed to merge this in?

**Comment by anusaini** [comment]
Nah. Merge this. We can always add/remove code later.

**Comment by gabrielcsapo** [comment]
@anusaini thoughts on this https://github.com/gabrielcsapo/turtler/pull/5/commits/e3fd9831d503965ec611dd5916ade446e4517723 it adds the header so the markdown tables look like 

```
| uid | name  |
|-----|-------|
| 1   | Doe   |
| 2   | Hemma |
```

which look like:

| uid | name  |
|-----|-------|
| 1   | Doe   |
| 2   | Hemma |

**Comment by gabrielcsapo** [comment]
@anusaini good to merge you think?

**Comment by anusaini** [comment]
Yeah. go ahead.

**Comment by dmikey** [comment]
`return (i === 0 ? '|' : '') + '-'.repeat(width + 2) + '|';`

This code is so hideous, I had to log in and comment on how bad this code stub is. Please save everyone and wrote an expanded form. The compiler can convert this to better code than you can, and future contributors will appreciate straight forward code.

**Comment by anusaini** [comment]
@dmikey Lol that's what you found hideous. This whole repo is so bad, I had half a mind to delete my GitHub account; leave development and live in Himalayas.

Mate chill and create a pull request.

**Comment by gabrielcsapo** [comment]
@anusaini the whole repo is bad?

**Comment by anusaini** [comment]
https://en.wikipedia.org/wiki/Reductio_ad_absurdum

**Pull request merged**
